@StoryId_349
Feature: 349-CalibrationCertificateUpload
    As a Service Provider
    I want to upload a calibration certificate for a selected piece of equipment
    So that I can store calibration certificates generated by third parties

@SingleInstrument
Scenario: Get to the Certificate Upload page
	Given I am signed in as 'sam.morris' with the password '!12345678A'
	And I am on the 'Instrument Details' page for '349-Test Instrument 1'
    And the 'Upload Certificate' button is displayed
	When I press the 'Upload Certificate' button
	Then I am on the 'New Certificate Upload' page

@SingleInstrument
Scenario: Cancel from Certificate Upload page
	Given I am signed in as 'sam.morris' with the password '!12345678A'
	And I am on the 'New Certificate Upload' page for '349-Test Instrument 1'
	When I press the 'Cancel' button
	Then I am on the 'Instrument Details' page for '349-Test Instrument 1'

@SingleInstrument
Scenario: Save empty form from Certificate Upload page
	Given I am signed in as 'sam.morris' with the password '!12345678A'
	And I am on the 'New Certificate Upload' page for '349-Test Instrument 1'
	When I press the 'Upload' button
	Then I am on the 'New Certificate Upload' page for '349-Test Instrument 1'
    And I am shown the message "Please enter a Certificate Number"
    And I am shown the message "Please enter a Start Date"
    And I am shown the message "Please enter a End Date"

@SingleInstrument
Scenario: Save form from New Certificate Upload page with invalid Start Date
	Given I am signed in as 'sam.morris' with the password '!12345678A'
	And I am on the 'New Certificate Upload' page for '349-Test Instrument 1'
    And I have entered 'abcdef' in the 'Start Date' textbox
    And I have entered '349-Test Certificate 1' in the 'Certificate Number' textbox
    And I have entered '01/12/2014' in the 'End Date' textbox
	When I press the 'Upload' button
	Then I am on the 'New Certificate Upload' page for '349-Test Instrument 1'
    And I am shown the message "The value 'abcdef' is not valid for Start Date."

@SingleInstrument
Scenario: Save form from New Certificate Upload page with invalid End Date
	Given I am signed in as 'sam.morris' with the password '!12345678A'
	And I am on the 'New Certificate Upload' page for '349-Test Instrument 1'
    And I have entered 'abcdef' in the 'End Date' textbox
    And I have entered '349-Test Certificate 1' in the 'Certificate Number' textbox
    And I have entered '01/12/2014' in the 'Start Date' textbox
	When I press the 'Upload' button
	Then I am on the 'New Certificate Upload' page for '349-Test Instrument 1'
    And I am shown the message "The value 'abcdef' is not valid for End Date."

@SingleInstrument
Scenario: Save form from New Certificate Upload page with  End Date < Start Date
	Given I am signed in as 'sam.morris' with the password '!12345678A'
	And I am on the 'New Certificate Upload' page for '349-Test Instrument 1'
    And I have entered '01/01/2015' in the 'Start Date' textbox
    And I have entered '349-Test Certificate 1' in the 'Certificate Number' textbox
    And I have entered '01/12/2014' in the 'End Date' textbox
	When I press the 'Upload' button
	Then I am on the 'New Certificate Upload' page for '349-Test Instrument 1'
    And I am shown the message "End Date must be after Start Date"

@SingleCalibrationCertificate
Scenario: Save form from New Certificate Upload page with existing Certificate Number
	Given I am signed in as 'sam.morris' with the password '!12345678A'
	And I am on the 'New Certificate Upload' page for '349-Test Instrument 1'
    And I have entered '349-Test Certificate 1' in the 'Certificate Number' textbox
    And I have entered '01/01/2014' in the 'Start Date' textbox
    And I have entered '01/12/2014' in the 'End Date' textbox
	When I press the 'Upload' button
	Then I am on the 'New Certificate Upload' page for '349-Test Instrument 1'
    And I am shown the message "A certificate with that Certificate Number already exists for this customer."

@SingleInstrument
Scenario: Save form from New Certificate Upload page with no file selected
	Given I am signed in as 'sam.morris' with the password '!12345678A'
	And I am on the 'New Certificate Upload' page for '349-Test Instrument 1'
    And I have entered '349-Test Certificate 1' in the 'Certificate Number' textbox
    And I have entered '01/01/2014' in the 'Start Date' textbox
    And I have entered '01/12/2014' in the 'End Date' textbox
    And In the 'Certificate' textbox I have selected a file that is not of type '.pdf'
	When I press the 'Upload' button
	Then I am on the 'New Certificate Upload' page for '349-Test Instrument 1'
    And I am shown the message "File must be of type .pdf"


@SingleInstrument
Scenario: Save form from New Certificate Upload page with invalid file type
	Given I am signed in as 'sam.morris' with the password '!12345678A'
	And I am on the 'New Certificate Upload' page for '349-Test Instrument 1'
    And I have entered '349-Test Certificate 1' in the 'Certificate Number' textbox
    And I have entered '01/01/2014' in the 'Start Date' textbox
    And I have entered '01/12/2014' in the 'End Date' textbox
    And In the 'Certificate' textbox I have selected a file that is not of type '.pdf'
	When I press the 'Upload' button
	Then I am on the 'New Certificate Upload' page for '349-Test Instrument 1'
    And I am shown the message "File must be of type .pdf"

@SingleInstrument
Scenario: Save complete form from New Certificate Upload page
	Given I am signed in as 'sam.morris' with the password '!12345678A'
	And I am on the 'New Certificate Upload' page for '349-Test Instrument 1'
    And I have entered '349-Test Certificate 1' in the 'Certificate Number' textbox
    And I have entered '01/01/2014' in the 'Start Date' textbox
    And I have entered '01/12/2014' in the 'End Date' textbox
    And In the 'Certificate' textbox I have selected a file that is of type '.pdf'
	When I press the 'Upload' button
	Then I am on the 'Instrument Details' page for '349-Test Instrument 1'
    And I am shown the message "Certificate 349-Test Certificate 1 uploaded successfully"
    And In the 'Certificates' panel there is a row for '349-Test Certificate 1'
