// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18444
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace EOS2.Web.BDD.Specs.ServiceProvider.Feature
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("419-EditPlantArea")]
    [NUnit.Framework.CategoryAttribute("StoryId_419")]
    public partial class _419_EditPlantAreaFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "419-EditPlantArea.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "419-EditPlantArea", "  As a Service Provider User\r\n  I want to edit a Plant Area \r\n  So that I can cha" +
                    "nge meta-data", ProgrammingLanguage.CSharp, new string[] {
                        "StoryId_419"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Cancel from Plant Area Details page")]
        [NUnit.Framework.CategoryAttribute("SinglePlantArea")]
        public virtual void CancelFromPlantAreaDetailsPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cancel from Plant Area Details page", new string[] {
                        "SinglePlantArea"});
#line 9
this.ScenarioSetup(scenarioInfo);
#line 10
 testRunner.Given("I am signed in as \'sam.morris\' with the password \'!12345678A\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 11
 testRunner.And("I am on the \'Plant Area Details\' page for customer \'419-Test Customer 1\', site \'4" +
                    "19-Test Site 1\' and plant area \'419-Test Plant Area 1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 12
 testRunner.When("I press the \'Cancel\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 13
 testRunner.Then("I am on the \'Site Details\' page for \'419-Test Site 1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Save empty form from Plant Area Details page")]
        [NUnit.Framework.CategoryAttribute("SinglePlantArea")]
        public virtual void SaveEmptyFormFromPlantAreaDetailsPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Save empty form from Plant Area Details page", new string[] {
                        "SinglePlantArea"});
#line 16
this.ScenarioSetup(scenarioInfo);
#line 17
 testRunner.Given("I am signed in as \'sam.morris\' with the password \'!12345678A\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 18
 testRunner.And("I am on the \'Plant Area Details\' page for customer \'419-Test Customer 1\', site \'4" +
                    "19-Test Site 1\' and plant area \'419-Test Plant Area 1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 19
    testRunner.And("I have cleared the \'Name\' textbox", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 20
    testRunner.And("I have cleared the \'Description\' textbox", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 21
 testRunner.When("I press the \'Save\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 22
 testRunner.Then("I am on the \'Plant Area Details\' page for customer \'419-Test Customer 1\', site \'4" +
                    "19-Test Site 1\' and plant area \'419-Test Plant Area 1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 23
    testRunner.And("I am shown the message \"Please enter the name for your plant area\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 24
    testRunner.And("I am shown the message \"Please enter the Description of your plant area\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Save form from Plant Area Details page with invalid name")]
        [NUnit.Framework.CategoryAttribute("SinglePlantArea")]
        public virtual void SaveFormFromPlantAreaDetailsPageWithInvalidName()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Save form from Plant Area Details page with invalid name", new string[] {
                        "SinglePlantArea"});
#line 27
this.ScenarioSetup(scenarioInfo);
#line 28
 testRunner.Given("I am signed in as \'sam.morris\' with the password \'!12345678A\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 29
 testRunner.And("I am on the \'Plant Area Details\' page for customer \'419-Test Customer 1\', site \'4" +
                    "19-Test Site 1\' and plant area \'419-Test Plant Area 1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 30
    testRunner.And("I have entered \'12345678901234567890123456789012345678901234567890123456789012345" +
                    "67890123456789012345678901234567890123456789012345678901\' in the \'Name\' textbox", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 31
 testRunner.When("I press the \'Save\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 32
 testRunner.Then("I am on the \'Plant Area Details\' page for customer \'419-Test Customer 1\', site \'4" +
                    "19-Test Site 1\' and plant area \'419-Test Plant Area 1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 33
    testRunner.And("I am shown the message \"Maximum Length is 120 Characters\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Save form from Plant Area Details page with existing name")]
        [NUnit.Framework.CategoryAttribute("MultiplePlantArea")]
        public virtual void SaveFormFromPlantAreaDetailsPageWithExistingName()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Save form from Plant Area Details page with existing name", new string[] {
                        "MultiplePlantArea"});
#line 36
this.ScenarioSetup(scenarioInfo);
#line 37
 testRunner.Given("I am signed in as \'sam.morris\' with the password \'!12345678A\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 38
 testRunner.And("I am on the \'Plant Area Details\' page for customer \'419-Test Customer 1\', site \'4" +
                    "19-Test Site 1\' and plant area \'419-Test Plant Area 1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 39
    testRunner.And("I have entered \'420-Test Plant Area 2\' in the \'Name\' textbox", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 40
 testRunner.When("I press the \'Save\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 41
 testRunner.Then("I am on the \'Plant Area Details\' page for customer \'419-Test Customer 1\', site \'4" +
                    "19-Test Site 1\' and plant area \'419-Test Plant Area 1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 42
    testRunner.And("I am shown the message \"A Plant Area with that name already exists\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Save complete form from Plant Area Details page")]
        [NUnit.Framework.CategoryAttribute("SinglePlantArea")]
        public virtual void SaveCompleteFormFromPlantAreaDetailsPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Save complete form from Plant Area Details page", new string[] {
                        "SinglePlantArea"});
#line 45
this.ScenarioSetup(scenarioInfo);
#line 46
 testRunner.Given("I am signed in as \'sam.morris\' with the password \'!12345678A\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 47
 testRunner.And("I am on the \'Plant Area Details\' page for customer \'419-Test Customer 1\', site \'4" +
                    "19-Test Site 1\' and plant area \'419-Test Plant Area 1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 48
    testRunner.And("I have entered \'Dummy Description 2\' in the \'Description\' textbox", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 49
 testRunner.When("I press the \'Save\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 50
 testRunner.Then("I am on the \'Plant Area Details\' page for customer \'419-Test Customer 1\', site \'4" +
                    "19-Test Site 1\' and plant area \'419-Test Plant Area 1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 51
    testRunner.And("I am shown the message \"Plant Area 416-Test Plant Area saved successfully\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
