// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18444
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace EOS2.Web.BDD.Specs.ServiceProvider.Feature
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("892-EditSchedule")]
    [NUnit.Framework.CategoryAttribute("StoryId_892")]
    public partial class _892_EditScheduleFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "892-EditSchedule.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "892-EditSchedule", "  As a Site Administrator or a Service Provider User\r\n  I want to be able to edit" +
                    " a TUS or SAT schedule for my equipment\r\n  So that I can facilitate planning of " +
                    "TUS or SAT surveys", ProgrammingLanguage.CSharp, new string[] {
                        "StoryId_892"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Get to Schedule Details page")]
        [NUnit.Framework.CategoryAttribute("SingleSchedule")]
        public virtual void GetToScheduleDetailsPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get to Schedule Details page", new string[] {
                        "SingleSchedule"});
#line 9
this.ScenarioSetup(scenarioInfo);
#line 10
 testRunner.Given("I am signed in as \'sam.morris\' with the password \'!12345678A\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 11
 testRunner.And("I am on the \'Equipment Details\' page for customer \'892-Test Customer 1\', site \'89" +
                    "2-Test Site 1\', plant area \'892-Test Plant Area 1\' and equipment \'892-Test Equip" +
                    "ment 1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 12
    testRunner.And("Schedule \'892-Test Schedule 1\' is listed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
    testRunner.And("Schedule \'892-Test Schedule 1\' has a \'Details\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
 testRunner.When("I press the \'Details\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 15
 testRunner.Then("I am on the \'Schedule Details\' page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 16
    testRunner.And("the \'Name\' textbox displays \'892-Test Schedule 1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 17
    testRunner.And("the \'Furnace Class\' dropdown displays \'-\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 18
    testRunner.And("the \'Description\' textbox displays \'Test Description 1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 19
    testRunner.And("the \'Schedule Type\' radio button displays \'SAT\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 20
    testRunner.And("the \'Frequency\' dropdown displays \'None\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 21
    testRunner.And("the \'Special Conditions\' textbox displays \'Test Special Conditions 1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Cancel from Schedule Details page")]
        [NUnit.Framework.CategoryAttribute("SingleSchedule")]
        public virtual void CancelFromScheduleDetailsPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cancel from Schedule Details page", new string[] {
                        "SingleSchedule"});
#line 24
this.ScenarioSetup(scenarioInfo);
#line 25
 testRunner.Given("I am signed in as \'sam.morris\' with the password \'!12345678A\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 26
 testRunner.And("I am on the \'Schedule Details\' page for customer \'892-Test Customer 1\', site \'892" +
                    "-Test Site 1\', plant area \'892-Test Plant Area 1\', equipment \'892-Test Equipment" +
                    " 1\' and Schedule \'892-Test Schedule 1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 27
 testRunner.When("I press the \'Cancel\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 28
 testRunner.Then("I am on the \'Equipment Details\' page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Save empty form from Schedule Details page")]
        [NUnit.Framework.CategoryAttribute("SingleSchedule")]
        public virtual void SaveEmptyFormFromScheduleDetailsPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Save empty form from Schedule Details page", new string[] {
                        "SingleSchedule"});
#line 31
this.ScenarioSetup(scenarioInfo);
#line 32
 testRunner.Given("I am signed in as \'sam.morris\' with the password \'!12345678A\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 33
 testRunner.And("I am on the \'Schedule Details\' page for customer \'892-Test Customer 1\', site \'892" +
                    "-Test Site 1\', plant area \'892-Test Plant Area 1\', equipment \'892-Test Equipment" +
                    " 1\' and Schedule \'892-Test Schedule 1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 34
    testRunner.And("I have cleared the \'Name\' textbox", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 35
    testRunner.And("I have selected \'Please Select ...\' in the \'Furnace Class\' dropdown", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 36
    testRunner.And("I have selected \'Please Select ...\' in the \'Frequency\' dropdown", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 37
 testRunner.When("I press the \'Save\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 38
 testRunner.Then("I am on the \'Schedule Details\' page for customer \'892-Test Customer 1\', site \'892" +
                    "-Test Site 1\', plant area \'892-Test Plant Area 1\', equipment \'892-Test Equipment" +
                    " 1\' and Schedule \'892-Test Schedule 1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 39
    testRunner.And("I am shown the message \"Please enter the name for your schedule\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 40
    testRunner.And("I am shown the message \"Please select a Furnace Class\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 41
    testRunner.And("I am shown the message \'Please select a Frequency\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Save form from Schedule Details page with invalid name")]
        [NUnit.Framework.CategoryAttribute("SingleSchedule")]
        public virtual void SaveFormFromScheduleDetailsPageWithInvalidName()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Save form from Schedule Details page with invalid name", new string[] {
                        "SingleSchedule"});
#line 44
this.ScenarioSetup(scenarioInfo);
#line 45
 testRunner.Given("I am signed in as \'sam.morris\' with the password \'!12345678A\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 46
 testRunner.And("I am on the \'Schedule Details\' page for customer \'892-Test Customer 1\', site \'892" +
                    "-Test Site 1\', plant area \'892-Test Plant Area 1\', equipment \'892-Test Equipment" +
                    " 1\' and Schedule \'892-Test Schedule 1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 47
    testRunner.And("I have entered \'12345678901234567890123456789012345678901234567890123456789012345" +
                    "67890123456789012345678901234567890123456789012345678901\' in the \'Name\' textbox", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 48
    testRunner.And("I have selected \'-\' in the \'Furnace Class\' dropdown", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 49
    testRunner.And("I have selected \'None\' in the \'Frequency\' dropdown", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 50
    testRunner.And("I have selected \'SAT\' in the \'Schedule Type\' radio button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 51
 testRunner.When("I press the \'Save\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 52
 testRunner.Then("I am on the \'Schedule Details\' page for customer \'892-Test Customer 1\', site \'892" +
                    "-Test Site 1\', plant area \'892-Test Plant Area 1\', equipment \'892-Test Equipment" +
                    " 1\' and Schedule \'892-Test Schedule 1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 53
    testRunner.And("I am shown the message \"Maximum Length is 120 Characters\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Save form from Schedule Details page with existing name")]
        [NUnit.Framework.CategoryAttribute("MultipleSchedule")]
        public virtual void SaveFormFromScheduleDetailsPageWithExistingName()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Save form from Schedule Details page with existing name", new string[] {
                        "MultipleSchedule"});
#line 56
this.ScenarioSetup(scenarioInfo);
#line 57
 testRunner.Given("I am signed in as \'sam.morris\' with the password \'!12345678A\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 58
 testRunner.And("I am on the \'Schedule Details\' page for customer \'892-Test Customer 1\', site \'892" +
                    "-Test Site 1\', plant area \'892-Test Plant Area 1\', equipment \'892-Test Equipment" +
                    " 1\' and Schedule \'892-Test Schedule 1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 59
    testRunner.And("I have entered \'892-Test Schedule 2\' in the \'Name\' textbox", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 60
    testRunner.And("I have selected \'5\' in the \'Furnace Class\' dropdown", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 61
    testRunner.And("I have selected \'Yearly\' in the \'Frequency\' dropdown", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 62
    testRunner.And("I have selected \'TUS\' in the \'Schedule Type\' radio button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 63
 testRunner.When("I press the \'Save\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 64
 testRunner.And("I am on the \'Schedule Details\' page for customer \'892-Test Customer 1\', site \'892" +
                    "-Test Site 1\', plant area \'892-Test Plant Area 1\', equipment \'892-Test Equipment" +
                    " 1\' and Schedule \'892-Test Schedule 1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 65
    testRunner.And("I am shown the message \"A Schedule with that Name already exists for this Equipme" +
                    "nt\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Save form from Schedule Details page with existing Schedule for Class and Type")]
        [NUnit.Framework.CategoryAttribute("MultipleSchedule")]
        public virtual void SaveFormFromScheduleDetailsPageWithExistingScheduleForClassAndType()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Save form from Schedule Details page with existing Schedule for Class and Type", new string[] {
                        "MultipleSchedule"});
#line 68
this.ScenarioSetup(scenarioInfo);
#line 69
 testRunner.Given("I am signed in as \'sam.morris\' with the password \'!12345678A\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 70
 testRunner.And("I am on the \'Schedule Details\' page for customer \'892-Test Customer 1\', site \'892" +
                    "-Test Site 1\', plant area \'892-Test Plant Area 1\', equipment \'892-Test Equipment" +
                    " 1\' and Schedule \'892-Test Schedule 1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 71
    testRunner.And("I have selected \'1\' in the \'Furnace Class\' dropdown", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 72
    testRunner.And("I have selected \'None\' in the \'Frequency\' dropdown", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 73
    testRunner.And("I have selected \'SAT\' in the \'Schedule Type\' radio button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 74
 testRunner.When("I press the \'Save\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 75
 testRunner.And("I am on the \'Schedule Details\' page for customer \'892-Test Customer 1\', site \'892" +
                    "-Test Site 1\', plant area \'892-Test Plant Area 1\', equipment \'892-Test Equipment" +
                    " 1\' and Schedule \'892-Test Schedule 1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 76
    testRunner.And("I am shown the message \"A Schedule of that Type & Furnace Class already exists fo" +
                    "r this Equipment\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Save complete form from Schedule Details page")]
        [NUnit.Framework.CategoryAttribute("SingleSchedule")]
        public virtual void SaveCompleteFormFromScheduleDetailsPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Save complete form from Schedule Details page", new string[] {
                        "SingleSchedule"});
#line 79
this.ScenarioSetup(scenarioInfo);
#line 80
 testRunner.Given("I am signed in as \'sam.morris\' with the password \'!12345678A\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 81
 testRunner.And("I am on the \'Schedule Details\' page for customer \'892-Test Customer 1\', site \'892" +
                    "-Test Site 1\', plant area \'892-Test Plant Area 1\', equipment \'892-Test Equipment" +
                    " 1\' and Schedule \'892-Test Schedule 1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 82
    testRunner.And("I have entered \'892-Test Schedule\' in the \'Name\' textbox", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 83
 testRunner.When("I press the \'Save\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 84
 testRunner.Then("I am on the \'Equipment Details\' page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 85
    testRunner.And("I am shown the message \"Schedule 892-Test Schedule saved successfully\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
