// <auto-generated />
namespace EOS2.Data.Migrations.EOS2DbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Equipments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Equipments));
        
        string IMigrationMetadata.Id
        {
            get { return "201410061224363_Equipments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
