// <auto-generated />
namespace EOS2.Data.Migrations.SecurityContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class NewUserFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewUserFields));
        
        string IMigrationMetadata.Id
        {
            get { return "201410271131212_NewUserFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
